import "../input.css"; // Tailwind CSS stylesheet

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <html lang="en">
        <head>
          <title>SmartCommerce AI</title>
          <meta name="description" content="SmartCommerce AI" />
          <link rel="icon" href="/favicon.ico" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <meta name="robots" content="index, follow" />
          <link rel="manifest" href="/manifest.json" />
          <link rel="apple-touch-icon" href="/apple-touch-icon.png" />
          <meta name="theme-color" content="#ffffff" />
        </head>
        <body>
          {children}
        </body>
      </html>
    </>
  );
}
